In [1]:
import pandas as pd
import numpy as np

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

d:\Semesters\6th_Sem\Minor Project\FairHire\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
import os

print(os.getcwd())

d:\Semesters\6th_Sem\Minor Project\FairHire\notebooks

In [3]:
job_df = pd.read_csv("../Data/job_description_dataset.csv")
resume_df = pd.read_csv("../Data/resume_dataset.csv")

print(job_df.shape)
print(resume_df.shape)

(1068, 7)
(10174, 5)

In [4]:
print("Job Columns:")
print(job_df.columns.tolist())

print("\nResume Columns:")
print(resume_df.columns.tolist())

Job Columns:
['JobID', 'Title', 'ExperienceLevel', 'YearsOfExperience', 'Skills', 'Responsibilities', 'Keywords']

Resume Columns:
['Role', 'Resume', 'Decision', 'Reason_for_decision', 'Job_Description']

In [5]:
job_df["Full_Job_Description"] = (
    job_df["Title"].astype(str) + " " +
    job_df["Skills"].astype(str) + " " +
    job_df["Responsibilities"].astype(str) + " " +
    job_df["Keywords"].astype(str)
)

In [6]:
print("===== JOB DESCRIPTION SAMPLE =====")
print(job_df["Full_Job_Description"].iloc[0][:1000])

print("\n")
print("===== RESUME SAMPLE =====")
print(resume_df["Resume"].iloc[0][:1000])

===== JOB DESCRIPTION SAMPLE =====
.NET Developer C#; VB.NET basics; .NET Framework; .NET Core fundamentals; ASP.NET; MVC; HTML; CSS; JavaScript basics; SQL Server; Entity Framework basics; LINQ; Visual Studio; Git; Unit Testing basics Assist in coding and debugging applications; Learn and apply .NET Framework and Core fundamentals; Support team in building ASP.NET MVC web applications; Write basic SQL queries and work with Entity Framework; Collaborate with peers to solve issues; Participate in code reviews for learning; Follow best practices in coding; Work with version control (Git) .NET; C#; ASP.NET MVC; Entity Framework; SQL Server; LINQ; Visual Studio; Unit Testing


===== RESUME SAMPLE =====
Here's a professional resume for Jason Jones:

Jason Jones
E-commerce Specialist

Contact Information:

* Email: [jasonjones@email.com](mailto:jasonjones@email.com)
* Phone: 555-123-4567
* LinkedIn: linkedin.com/in/jasonjones

Summary:
Results-driven E-commerce Specialist with 5+ years of experience in inventory management, SEO, online advertising, and analytics. Proven track record of increasing online sales, improving website traffic, and optimizing inventory levels. Skilled in analyzing complex data sets, identifying trends, and making data-driven decisions. Passionate about staying up-to-date with the latest e-commerce trends and technologies.

Professional Experience:

E-commerce Specialist, XYZ Corporation (2018-Present)

* Managed inventory levels across multiple channels, resulting in a 25% reduction in stockouts and a 15% reduction in overstocking
* Developed and implemented SEO strategies that increased website traffic by 30% and improved search engine rankings by 20%
* Creat

In [ ]:
sample_job = job_df["Full_Job_Description"].iloc[0]

sample_resumes = resume_df["Resume"].head(5)

print("Job Loaded Successfully")
print("Number of Resumes:", len(sample_resumes))

Job Loaded Successfully
Number of Resumes: 5

In [8]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

print("Model Loaded Successfully")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3612.76it/s]

Model Loaded Successfully

In [ ]:
job_embedding = model.encode(sample_job)

resume_embeddings = model.encode(
    sample_resumes.tolist()
)

print("Job Embedding Shape:", job_embedding.shape)
print("Number of Resume Embeddings:", len(resume_embeddings))

Job Embedding Shape: (384,)
Number of Resume Embeddings: 5

In [10]:
from sklearn.metrics.pairwise import cosine_similarity

scores = []

for i, resume_embedding in enumerate(resume_embeddings):

    similarity = cosine_similarity(
        [job_embedding],
        [resume_embedding]
    )[0][0]

    scores.append(
        {
            "Resume_ID": i + 1,
            "Similarity_Score": similarity
        }
    )

scores

[{'Resume_ID': 1, 'Similarity_Score': np.float32(0.19756836)},
 {'Resume_ID': 2, 'Similarity_Score': np.float32(0.25953352)},
 {'Resume_ID': 3, 'Similarity_Score': np.float32(0.15382609)},
 {'Resume_ID': 4, 'Similarity_Score': np.float32(0.12250352)},
 {'Resume_ID': 5, 'Similarity_Score': np.float32(0.14186576)}]

In [24]:
scores_df["Match_Percentage"] = (
    scores_df["Similarity_Score"] * 100
).round(2)

scores_df

   Resume_ID  Similarity_Score  Match_Percentage
8          9          0.379532         37.950001
3          4          0.350658         35.070000
0          1          0.348683         34.869999
4          5          0.336445         33.639999
7          8          0.329055         32.910000
6          7          0.328073         32.810001
2          3          0.315966         31.600000
1          2          0.308430         30.840000
9         10          0.300515         30.049999
5          6          0.278934         27.889999

In [ ]:
for i in range(5):
    print(f"\nResume {i+1}")
    print("=" * 50)
    print("Role:", resume_df.iloc[i]["Role"])

Resume 1
==================================================
Role: E-commerce Specialist

Resume 2
==================================================
Role: Game Developer

Resume 3
==================================================
Role: Human Resources Specialist

Resume 4
==================================================
Role: E-commerce Specialist

Resume 5
==================================================
Role: E-commerce Specialist

In [ ]:
resume_df["Role"].value_counts().head(20)

Role
Data Scientist                  538
Software Engineer               480
Product Manager                 458
Data Engineer                   447
UI Engineer                     375
Data Analyst                    329
software engineer               307
data engineer                   307
product manager                 303
data scientist                  287
E-commerce Specialist           268
DevOps Engineer                 266
Machine Learning Engineer       265
Human Resources Specialist      262
Digital Marketing Specialist    260
Robotics Engineer               257
Cloud Architect                 254
QA Engineer                     251
Blockchain Developer            251
Mobile App Developer            247
Name: count, dtype: int64

## Next Task (Cell 14)
Let's find Software Engineer resumes.

In [ ]:
software_resumes = resume_df[
    resume_df["Role"].str.lower() == "software engineer"
]

print("Number of Software Engineer Resumes:")
print(len(software_resumes))

software_resumes.head()

Number of Software Engineer Resumes:
787

,Role,Resume,Decision,Reason_for_decision,Job_Description
68,Software Engineer,Here's a professional resume for David Rivera:...,select,Perfectly aligned with data engineering needs.,We need a Software Engineer to enhance our tea...
117,Software Engineer,Here's a sample resume for Brian Hicks:\n\nBri...,select,Impressive leadership and communication abilit...,If you're passionate about software engineerin...
125,Software Engineer,Here's a sample resume for Jeffrey Stephenson:...,reject,Insufficient system design expertise for senio...,We're hiring a Software Engineer to develop an...
127,Software Engineer,Here's a sample resume for Tammy Hamilton:\n\n...,reject,Lacks hands-on experience with cloud platforms.,We are looking for an experienced Software Eng...
166,Software Engineer,Here's a sample resume for Gregory Saunders:\n...,select,Excellent full-stack development experience.,Join our fast-growing team and help us scale o...

In [ ]:
sample_resumes = software_resumes["Resume"].head(10)

print("Number of Selected Resumes:", len(sample_resumes))

Number of Selected Resumes: 10

In [23]:
print(sample_resumes.shape)

for i in range(3):
    print("\nResume", i+1)
    print("="*50)
    print(sample_resumes.iloc[i][:300])

(10,)

Resume 1
==================================================
Here's a professional resume for David Rivera:

David Rivera
Software Engineer

Contact Information:

* Phone: (555) 123-4567
* Email: [david.rivera@email.com](mailto:david.rivera@email.com)
* LinkedIn: linkedin.com/in/davidriverasoftware
* GitHub: github.com/davidriverasoftware

Summary:

Highly mo

Resume 2
==================================================
Here's a sample resume for Brian Hicks:

Brian Hicks
Software Engineer

Contact Information:

* Email: [brian.hicks@email.com](mailto:brian.hicks@email.com)
* Phone: 555-555-5555
* LinkedIn: linkedin.com/in/brianhickssoftware
* GitHub: github.com/brianhicks

Summary:
Highly motivated and detail-orie

Resume 3
==================================================
Here's a sample resume for Jeffrey Stephenson:

Jeffrey Stephenson
Software Engineer

Contact Information:

* Email: [jeffrey.stephenson@email.com](mailto:jeffrey.stephenson@email.com)
* Phone: (123) 456-7890
* LinkedIn: linkedin.com/in/jeffrey-stephenson
* GitHub: github.com/jeffrey-stephenson

Pro

In [18]:
job_embedding = model.encode(sample_job)

resume_embeddings = model.encode(
    sample_resumes.tolist()
)

In [19]:
scores = []

for i, resume_embedding in enumerate(resume_embeddings):

    similarity = cosine_similarity(
        [job_embedding],
        [resume_embedding]
    )[0][0]

    scores.append(
        {
            "Resume_ID": i + 1,
            "Similarity_Score": similarity
        }
    )

scores_df = pd.DataFrame(scores)

scores_df["Match_Percentage"] = (
    scores_df["Similarity_Score"] * 100
).round(2)

scores_df = scores_df.sort_values(
    by="Similarity_Score",
    ascending=False
)

scores_df

   Resume_ID  Similarity_Score  Match_Percentage
8          9          0.379532         37.950001
3          4          0.350658         35.070000
0          1          0.348683         34.869999
4          5          0.336445         33.639999
7          8          0.329055         32.910000
6          7          0.328073         32.810001
2          3          0.315966         31.600000
1          2          0.308430         30.840000
9         10          0.300515         30.049999
5          6          0.278934         27.889999

In [21]:
software_resumes["Role"].head(10)

68     Software Engineer
117    Software Engineer
125    Software Engineer
127    Software Engineer
166    Software Engineer
170    Software Engineer
192    Software Engineer
219    Software Engineer
236    Software Engineer
254    Software Engineer
Name: Role, dtype: str

In [22]:
sample_resumes = software_resumes["Resume"].head(10)

job_embedding = model.encode(sample_job)

resume_embeddings = model.encode(
    sample_resumes.tolist()
)

In [31]:
scores_df.reset_index(drop=True, inplace=True)

scores_df.index = scores_df.index + 1

scores_df.rename_axis("Rank", inplace=True)

scores_df

      Resume_ID  Similarity_Score  Match_Percentage
Rank
1             9          0.379532         37.950001
2             4          0.350658         35.070000
3             1          0.348683         34.869999
4             5          0.336445         33.639999
5             8          0.329055         32.910000
6             7          0.328073         32.810001
7             3          0.315966         31.600000
8             2          0.308430         30.840000
9            10          0.300515         30.049999
10            6          0.278934         27.889999

In [33]:
scores_df.to_csv(
    "../Data/software_engineer_matching_results.csv",
    index=False
)

print("Results Saved Successfully")

Results Saved Successfully